# Run style checks

name: style

on:
  - pull_request
  - workflow_dispatch

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          cache-dependency-path: ".github/workflows/qc-requirements.txt"
      - run: python -m pip install -r .github/workflows/qc-requirements.txt
      - run: python -m pip install .
      - name: Run style checks
        run: |
          python -m ruff format --check --diff
          python -m ruff check
